../include/core_pkg.sv
../include/riscv_pkg.sv
../synthesis/decoder.sv
../synthesis/imm_gen.sv
../synthesis/id_stage.sv
../synthesis/mem_sync_sp.sv
../synthesis/if_stage.sv
../synthesis/regfile_2r1w.sv
../synthesis/ex_stage.sv
../synthesis/alu.sv
../synthesis/branch_unit.sv
