../include/core_pkg.sv
../include/riscv_pkg.sv
../synthesis/decoder.sv
../synthesis/imm_gen.sv
../synthesis/id_stage.sv
../synthesis/mem_sync_sp.sv
../synthesis/if_stage.sv
../synthesis/regfile_2r1w.sv
../synthesis/ex_stage.sv
../synthesis/alu.sv
../synthesis/branch_unit.sv
../synthesis/memory_unit.sv
../synthesis/mem_sync_sp_rvdmem.sv
../synthesis/mem_stage.sv
../synthesis/store_cntrl.sv
../synthesis/load_cntrl.sv
../synthesis/mem_signext.sv
../synthesis/wb_stage.sv
../synthesis/stall_controller.sv
../synthesis/fw_controller.sv