#! /bin/bash
cd  ../../../code/compliance_tests &&
source ../rv32i-settings.sh &&
make clean && make &&
cp "$1".imem.dat  ../../project/RISC-V-Core/code/ihex/code.hex 
cp "$1".dmem.dat ../../project/RISC-V-Core/code/ihex/codemem.hex 


echo done!

